// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260926163309_AddMaterialConversionProvenance")]
partial class AddMaterialConversionProvenance
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("public")
            .HasAnnotation("ProductVersion", "10.0.9")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Domain.Assets.Asset", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<DateOnly>("AcquisitionDate").HasColumnType("date").HasColumnName("acquisition_date");
                b.Property<string>("AssetNumber").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("asset_number");
                b.Property<Guid>("MaterialId").HasColumnType("uuid").HasColumnName("material_id");
                b.Property<Guid?>("ReceiptLineId").HasColumnType("uuid").HasColumnName("receipt_line_id");
                b.Property<int>("RowVersion").IsConcurrencyToken().HasColumnType("integer").HasColumnName("row_version");
                b.Property<string>("SerialNumber").HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("serial_number");
                b.Property<Guid?>("WarehouseId").HasColumnType("uuid").HasColumnName("warehouse_id");
                b.Property<DateOnly?>("WarrantyExpiry").HasColumnType("date").HasColumnName("warranty_expiry");
                b.HasKey("Id").HasName("pk_assets");
                b.HasIndex("AssetNumber").IsUnique().HasDatabaseName("ix_assets_asset_number");
                b.HasIndex("MaterialId").HasDatabaseName("ix_assets_material_id");
                b.HasIndex("ReceiptLineId").HasDatabaseName("ix_assets_receipt_line_id");
                b.HasIndex("ReceiptLineId", "MaterialId").HasDatabaseName("ix_assets_receipt_line_id_material_id");
                b.HasIndex("WarehouseId", "MaterialId").HasDatabaseName("ix_assets_warehouse_id_material_id");
                b.ToTable("assets", "public", t =>
                    {
                        t.HasCheckConstraint("ck_assets_asset_number_not_blank", "length(btrim(asset_number)) > 0");
                        t.HasCheckConstraint("ck_assets_row_version_positive", "row_version > 0");
                        t.HasCheckConstraint("ck_assets_warranty_after_acquisition", "warranty_expiry IS NULL OR warranty_expiry >= acquisition_date");
                    });
            });

        modelBuilder.Entity("Domain.DocumentLines.DocumentLine", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<decimal>("BaseQuantity").HasPrecision(18, 3).HasColumnType("numeric(18,3)").HasColumnName("base_quantity");
                b.Property<string>("BatchNumber").HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("batch_number");
                b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("created_at_utc");
                b.Property<Guid?>("CreatedBy").HasColumnType("uuid").HasColumnName("created_by");
                b.Property<Guid>("DocumentId").HasColumnType("uuid").HasColumnName("document_id");
                b.Property<DateOnly?>("ExpiryDate").HasColumnType("date").HasColumnName("expiry_date");
                b.Property<string>("LineType").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("line_type");
                b.Property<Guid>("MaterialId").HasColumnType("uuid").HasColumnName("material_id");
                b.Property<string>("OpeningType").HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("opening_type");
                b.Property<decimal>("Quantity").HasPrecision(18, 3).HasColumnType("numeric(18,3)").HasColumnName("quantity");
                b.Property<Guid?>("SourceBaseUnitId").HasColumnType("uuid").HasColumnName("source_base_unit_id");
                b.Property<decimal?>("SourceConversionFactor").HasPrecision(18, 6).HasColumnType("numeric(18,6)").HasColumnName("source_conversion_factor");
                b.Property<Guid?>("SourceConversionFromUnitId").HasColumnType("uuid").HasColumnName("source_conversion_from_unit_id");
                b.Property<Guid?>("SourceConversionId").HasColumnType("uuid").HasColumnName("source_conversion_id");
                b.Property<Guid?>("SourceConversionToUnitId").HasColumnType("uuid").HasColumnName("source_conversion_to_unit_id");
                b.Property<Guid?>("SourceLineId").HasColumnType("uuid").HasColumnName("source_line_id");
                b.Property<string>("SourceMaterialKind").HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("source_material_kind");
                b.Property<int?>("SourceMaterialVersion").HasColumnType("integer").HasColumnName("source_material_version");
                b.Property<string>("SourceTrackingType").HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("source_tracking_type");
                b.Property<Guid?>("UnitId").HasColumnType("uuid").HasColumnName("unit_id");
                b.Property<decimal?>("UnitPrice").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("unit_price");
                b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("updated_at_utc");
                b.Property<Guid?>("UpdatedBy").HasColumnType("uuid").HasColumnName("updated_by");
                b.HasKey("Id").HasName("pk_document_lines");
                b.HasAlternateKey("Id", "DocumentId").HasName("ak_document_lines_id_document_id");
                b.HasAlternateKey("Id", "MaterialId").HasName("ak_document_lines_id_material_id");
                b.HasAlternateKey("Id", "DocumentId", "MaterialId").HasName("ak_document_lines_id_document_id_material_id");
                b.HasIndex("DocumentId").HasDatabaseName("ix_document_lines_document_id");
                b.HasIndex("MaterialId").HasDatabaseName("ix_document_lines_material_id");
                b.HasIndex("SourceConversionId").HasDatabaseName("ix_document_lines_source_conversion_id");
                b.HasIndex("SourceLineId").IsUnique().HasDatabaseName("ix_document_lines_source_line_id").HasFilter("source_line_id IS NOT NULL");
                b.HasIndex("UnitId").HasDatabaseName("ix_document_lines_unit_id");
                b.HasIndex("DocumentId", "MaterialId").HasDatabaseName("ix_document_lines_document_id_material_id");
                b.HasIndex("DocumentId", "SourceMaterialVersion").HasDatabaseName("ix_document_lines_document_id_source_material_version");
                b.ToTable("document_lines", "public", t =>
                    {
                        t.HasCheckConstraint("ck_document_lines_base_quantity_positive", "base_quantity > 0");
                        t.HasCheckConstraint("ck_document_lines_line_type_valid", "line_type IN ('Normal', 'Asset')");
                        t.HasCheckConstraint("ck_document_lines_opening_type_valid", "opening_type IS NULL OR opening_type IN ('Initial', 'Correction')");
                        t.HasCheckConstraint("ck_document_lines_quantity_positive", "quantity > 0");
                        t.HasCheckConstraint("ck_document_lines_source_conversion_complete", "(source_conversion_id IS NULL AND source_conversion_from_unit_id IS NULL AND source_conversion_to_unit_id IS NULL AND source_conversion_factor IS NULL) OR (source_conversion_id IS NOT NULL AND source_conversion_from_unit_id IS NOT NULL AND source_conversion_to_unit_id IS NOT NULL AND source_conversion_factor IS NOT NULL AND source_conversion_factor > 0)");
                        t.HasCheckConstraint("ck_document_lines_source_conversion_required", "source_material_version IS NULL OR source_base_unit_id IS NULL OR unit_id IS NULL OR unit_id = source_base_unit_id OR source_conversion_id IS NOT NULL");
                        t.HasCheckConstraint("ck_document_lines_source_material_version_positive", "source_material_version IS NULL OR source_material_version > 0");
                        t.HasCheckConstraint("ck_document_lines_source_provenance_complete", "(source_material_version IS NULL AND source_material_kind IS NULL AND source_tracking_type IS NULL AND source_base_unit_id IS NULL) OR (source_material_version IS NOT NULL AND source_material_version > 0 AND source_material_kind IS NOT NULL AND source_material_kind IN ('Consumable', 'Durable', 'Asset') AND source_tracking_type IS NOT NULL AND source_tracking_type IN ('Quantity', 'Serial') AND source_base_unit_id IS NOT NULL AND source_base_unit_id <> '00000000-0000-0000-0000-000000000000'::uuid)");
                        t.HasCheckConstraint("ck_document_lines_unit_price_non_negative", "unit_price >= 0");
                    });
            });

        modelBuilder.Entity("Domain.Materials.Material", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("Attributes").HasColumnType("jsonb").HasColumnName("attributes");
                b.Property<Guid>("BaseUnitId").HasColumnType("uuid").HasColumnName("base_unit_id");
                b.Property<int>("CatalogVersion").IsConcurrencyToken().HasColumnType("integer").HasColumnName("catalog_version");
                b.Property<string>("Code").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("code");
                b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("created_at_utc");
                b.Property<Guid?>("CreatedBy").HasColumnType("uuid").HasColumnName("created_by");
                b.Property<Guid>("FamilyId").HasColumnType("uuid").HasColumnName("family_id");
                b.Property<bool>("HasExpiry").HasColumnType("boolean").HasColumnName("has_expiry");
                b.Property<string>("MaterialKind").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("material_kind");
                b.Property<string>("NameAr").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("name_ar");
                b.Property<string>("NameEn").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("name_en");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("status");
                b.Property<string>("TrackingType").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("tracking_type");
                b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("updated_at_utc");
                b.Property<Guid?>("UpdatedBy").HasColumnType("uuid").HasColumnName("updated_by");
                b.HasKey("Id").HasName("pk_materials");
                b.HasIndex("BaseUnitId").HasDatabaseName("ix_materials_base_unit_id");
                b.HasIndex("Code").IsUnique().HasDatabaseName("ix_materials_code");
                b.HasIndex("FamilyId").HasDatabaseName("ix_materials_family_id");
                b.ToTable("materials", "public", t =>
                    {
                        t.HasCheckConstraint("ck_materials_catalog_version_positive", "catalog_version > 0");
                    });
            });

        modelBuilder.Entity("Domain.UnitsOfMeasure.UnitOfMeasure", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("created_at_utc");
                b.Property<Guid?>("CreatedBy").HasColumnType("uuid").HasColumnName("created_by");
                b.Property<string>("Name").IsRequired().HasColumnType("text").HasColumnName("name");
                b.Property<string>("Symbol").IsRequired().HasColumnType("text").HasColumnName("symbol");
                b.Property<string>("UnitType").IsRequired().HasColumnType("text").HasColumnName("unit_type");
                b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("updated_at_utc");
                b.Property<Guid?>("UpdatedBy").HasColumnType("uuid").HasColumnName("updated_by");
                b.HasKey("Id").HasName("pk_units_of_measure");
                b.ToTable("units_of_measure", "public");
            });

        modelBuilder.Entity("Domain.WarehouseDocuments.WarehouseDocument", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("DocumentNumber").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("document_number");
                b.Property<string>("DocumentType").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("document_type");
                b.Property<string>("DocumentStatus").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("document_status");
                b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("created_at_utc");
                b.Property<Guid?>("CreatedBy").HasColumnType("uuid").HasColumnName("created_by");
                b.Property<DateOnly?>("DocumentDate").HasColumnType("date").HasColumnName("document_date");
                b.Property<string>("PaperReference").HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("paper_reference");
                b.Property<int?>("PaperYear").HasColumnType("integer").HasColumnName("paper_year");
                b.Property<Guid?>("ReversalOfDocumentId").HasColumnType("uuid").HasColumnName("reversal_of_document_id");
                b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("updated_at_utc");
                b.Property<Guid?>("UpdatedBy").HasColumnType("uuid").HasColumnName("updated_by");
                b.Property<Guid>("WarehouseId").HasColumnType("uuid").HasColumnName("warehouse_id");
                b.Property<int>("RowVersion").IsConcurrencyToken().HasColumnType("integer").HasColumnName("row_version");
                b.HasKey("Id").HasName("pk_warehouse_documents");
                b.HasIndex("DocumentNumber").IsUnique().HasDatabaseName("ix_warehouse_documents_document_number");
                b.HasIndex("ReversalOfDocumentId").HasDatabaseName("ix_warehouse_documents_reversal_of_document_id");
                b.HasIndex("WarehouseId").HasDatabaseName("ix_warehouse_documents_warehouse_id");
                b.ToTable("warehouse_documents", "public", t =>
                    {
                        t.HasCheckConstraint("ck_warehouse_documents_document_type_valid", "document_type IN ('Receiving', 'Issue', 'Transfer', 'Adjustment', 'Opening', 'Return')");
                        t.HasCheckConstraint("ck_warehouse_documents_document_status_valid", "document_status IN ('Draft', 'Submitted', 'Posted', 'Cancelled', 'Reversed')");
                    });
            });

        modelBuilder.Entity("Domain.MaterialFamilies.MaterialFamily", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("CategoryId").HasColumnType("uuid").HasColumnName("category_id");
                b.Property<string>("Code").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("code");
                b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("created_at_utc");
                b.Property<Guid?>("CreatedBy").HasColumnType("uuid").HasColumnName("created_by");
                b.Property<string>("NameAr").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("name_ar");
                b.Property<string>("NameEn").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("name_en");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("status");
                b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("updated_at_utc");
                b.Property<Guid?>("UpdatedBy").HasColumnType("uuid").HasColumnName("updated_by");
                b.HasKey("Id").HasName("pk_material_families");
                b.HasIndex("CategoryId").HasDatabaseName("ix_material_families_category_id");
                b.HasIndex("Code").IsUnique().HasDatabaseName("ix_material_families_code");
                b.ToTable("material_families", "public", t =>
                    {
                        t.HasCheckConstraint("ck_material_families_status_valid", "status IN ('Active', 'Archived')");
                    });
            });

        modelBuilder.Entity("Domain.MaterialCategories.MaterialCategory", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("Code").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("code");
                b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("created_at_utc");
                b.Property<Guid?>("CreatedBy").HasColumnType("uuid").HasColumnName("created_by");
                b.Property<Guid>("DomainId").HasColumnType("uuid").HasColumnName("domain_id");
                b.Property<string>("NameAr").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("name_ar");
                b.Property<string>("NameEn").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("name_en");
                b.Property<Guid?>("ParentCategoryId").HasColumnType("uuid").HasColumnName("parent_category_id");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("status");
                b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("updated_at_utc");
                b.Property<Guid?>("UpdatedBy").HasColumnType("uuid").HasColumnName("updated_by");
                b.HasKey("Id").HasName("pk_material_categories");
                b.HasIndex("Code").IsUnique().HasDatabaseName("ix_material_categories_code");
                b.HasIndex("DomainId").HasDatabaseName("ix_material_categories_domain_id");
                b.HasIndex("ParentCategoryId").HasDatabaseName("ix_material_categories_parent_category_id");
                b.ToTable("material_categories", "public", t =>
                    {
                        t.HasCheckConstraint("ck_material_categories_status_valid", "status IN ('Active', 'Archived')");
                    });
            });

        modelBuilder.Entity("Domain.MaterialDomains.MaterialDomain", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("Code").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("code");
                b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("created_at_utc");
                b.Property<Guid?>("CreatedBy").HasColumnType("uuid").HasColumnName("created_by");
                b.Property<string>("NameAr").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("name_ar");
                b.Property<string>("NameEn").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("name_en");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("status");
                b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("updated_at_utc");
                b.Property<Guid?>("UpdatedBy").HasColumnType("uuid").HasColumnName("updated_by");
                b.HasKey("Id").HasName("pk_material_domains");
                b.HasIndex("Code").IsUnique().HasDatabaseName("ix_material_domains_code");
                b.ToTable("material_domains", "public", t =>
                    {
                        t.HasCheckConstraint("ck_material_domains_status_valid", "status IN ('Active', 'Archived')");
                    });
            });

        modelBuilder.Entity("Domain.MaterialUnitConversions.MaterialUnitConversion", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("created_at_utc");
                b.Property<Guid?>("CreatedBy").HasColumnType("uuid").HasColumnName("created_by");
                b.Property<decimal>("Factor").HasPrecision(18, 6).HasColumnType("numeric(18,6)").HasColumnName("factor");
                b.Property<Guid>("FromUnitId").HasColumnType("uuid").HasColumnName("from_unit_id");
                b.Property<bool>("IsActive").HasColumnType("boolean").HasColumnName("is_active");
                b.Property<Guid>("MaterialId").HasColumnType("uuid").HasColumnName("material_id");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("name");
                b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("updated_at_utc");
                b.Property<Guid?>("UpdatedBy").HasColumnType("uuid").HasColumnName("updated_by");
                b.Property<Guid>("ToBaseUnitId").HasColumnType("uuid").HasColumnName("to_base_unit_id");
                b.HasKey("Id").HasName("pk_material_unit_conversions");
                b.HasIndex("FromUnitId").HasDatabaseName("ix_material_unit_conversions_from_unit_id");
                b.HasIndex("MaterialId").HasDatabaseName("ix_material_unit_conversions_material_id");
                b.HasIndex("ToBaseUnitId").HasDatabaseName("ix_material_unit_conversions_to_base_unit_id");
                b.ToTable("material_unit_conversions", "public", t =>
                    {
                        t.HasCheckConstraint("ck_material_unit_conversions_positive_factor", "factor > 0");
                    });
            });

        modelBuilder.Entity("Domain.StockMovements.StockMovement", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("created_at_utc");
                b.Property<Guid?>("CreatedBy").HasColumnType("uuid").HasColumnName("created_by");
                b.Property<decimal>("DeltaQuantity").HasPrecision(18, 3).HasColumnType("numeric(18,3)").HasColumnName("delta_quantity");
                b.Property<Guid>("DocumentId").HasColumnType("uuid").HasColumnName("document_id");
                b.Property<Guid>("LineId").HasColumnType("uuid").HasColumnName("line_id");
                b.Property<string>("MovementType").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("movement_type");
                b.Property<Guid>("MaterialId").HasColumnType("uuid").HasColumnName("material_id");
                b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("updated_at_utc");
                b.Property<Guid?>("UpdatedBy").HasColumnType("uuid").HasColumnName("updated_by");
                b.Property<Guid>("WarehouseId").HasColumnType("uuid").HasColumnName("warehouse_id");
                b.HasKey("Id").HasName("pk_stock_movements");
                b.HasIndex("DocumentId").HasDatabaseName("ix_stock_movements_document_id");
                b.HasIndex("LineId").HasDatabaseName("ix_stock_movements_line_id");
                b.HasIndex("MaterialId").HasDatabaseName("ix_stock_movements_material_id");
                b.HasIndex("WarehouseId").HasDatabaseName("ix_stock_movements_warehouse_id");
                b.ToTable("stock_movements", "public", t =>
                    {
                        t.HasCheckConstraint("ck_stock_movements_movement_type_valid", "movement_type IN ('Receipt', 'Issue', 'Transfer', 'Adjustment', 'Opening', 'Return')");
                    });
            });

        modelBuilder.Entity("Domain.AssetMovementHistories.AssetMovementHistory", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("AssetId").HasColumnType("uuid").HasColumnName("asset_id");
                b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("created_at_utc");
                b.Property<Guid?>("CreatedBy").HasColumnType("uuid").HasColumnName("created_by");
                b.Property<Guid>("DocumentId").HasColumnType("uuid").HasColumnName("document_id");
                b.Property<DateTime>("MovedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("moved_at_utc");
                b.Property<string>("MovementType").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)").HasColumnName("movement_type");
                b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("updated_at_utc");
                b.Property<Guid?>("UpdatedBy").HasColumnType("uuid").HasColumnName("updated_by");
                b.HasKey("Id").HasName("pk_asset_movement_history");
                b.HasIndex("DocumentId").HasDatabaseName("ix_asset_movement_history_document_id");
                b.HasIndex("AssetId", "DocumentId", "MovementType").IsUnique().HasDatabaseName("ix_asset_movement_history_asset_id_document_id_movement_type");
                b.HasIndex("AssetId", "MovedAtUtc", "Id").HasDatabaseName("ix_asset_movement_history_asset_id_moved_at_utc_id");
                b.ToTable("asset_movement_history", "public", t =>
                    {
                        t.HasCheckConstraint("ck_asset_movement_history_type_valid", "movement_type IN ('Received', 'Transferred', 'Issued', 'Returned', 'Disposed')");
                    });
            });

        modelBuilder.Entity("Domain.DocumentLines.DocumentLine", b =>
            {
                b.HasOne("Domain.DocumentLines.DocumentLine", null).WithMany().HasForeignKey("SourceLineId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Domain.Materials.Material", null).WithMany().HasForeignKey("MaterialId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Domain.UnitsOfMeasure.UnitOfMeasure", null).WithMany().HasForeignKey("UnitId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Domain.WarehouseDocuments.WarehouseDocument", null).WithMany().HasForeignKey("DocumentId").OnDelete(DeleteBehavior.Restrict);
            });

        modelBuilder.Entity("Domain.Materials.Material", b =>
            {
                b.HasOne("Domain.MaterialFamilies.MaterialFamily", null).WithMany().HasForeignKey("FamilyId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Domain.UnitsOfMeasure.UnitOfMeasure", null).WithMany().HasForeignKey("BaseUnitId").OnDelete(DeleteBehavior.Restrict);
            });

        modelBuilder.Entity("Domain.MaterialFamilies.MaterialFamily", b =>
            {
                b.HasOne("Domain.MaterialCategories.MaterialCategory", null).WithMany().HasForeignKey("CategoryId").OnDelete(DeleteBehavior.Restrict);
            });

        modelBuilder.Entity("Domain.MaterialCategories.MaterialCategory", b =>
            {
                b.HasOne("Domain.MaterialDomains.MaterialDomain", null).WithMany().HasForeignKey("DomainId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Domain.MaterialCategories.MaterialCategory", null).WithMany().HasForeignKey("ParentCategoryId").OnDelete(DeleteBehavior.Restrict);
            });

        modelBuilder.Entity("Domain.StockMovements.StockMovement", b =>
            {
                b.HasOne("Domain.WarehouseDocuments.WarehouseDocument", null).WithMany().HasForeignKey("DocumentId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Domain.DocumentLines.DocumentLine", null).WithMany().HasForeignKey("LineId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Domain.Materials.Material", null).WithMany().HasForeignKey("MaterialId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Domain.Warehouses.Warehouse", null).WithMany().HasForeignKey("WarehouseId").OnDelete(DeleteBehavior.Restrict);
            });

        modelBuilder.Entity("Domain.AssetMovementHistories.AssetMovementHistory", b =>
            {
                b.HasOne("Domain.Assets.Asset", null).WithMany().HasForeignKey("AssetId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Domain.WarehouseDocuments.WarehouseDocument", null).WithMany().HasForeignKey("DocumentId").OnDelete(DeleteBehavior.Restrict);
            });

        modelBuilder.Entity("Domain.Assets.Asset", b =>
            {
                b.HasOne("Domain.Materials.Material", null).WithMany().HasForeignKey("MaterialId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Domain.DocumentLines.DocumentLine", null).WithMany().HasForeignKey("ReceiptLineId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Domain.Warehouses.Warehouse", null).WithMany().HasForeignKey("WarehouseId").OnDelete(DeleteBehavior.Restrict);
            });

        modelBuilder.Entity("Domain.WarehouseDocuments.WarehouseDocument", b =>
            {
                b.HasOne("Domain.Warehouses.Warehouse", null).WithMany().HasForeignKey("WarehouseId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Domain.WarehouseDocuments.WarehouseDocument", null).WithMany().HasForeignKey("ReversalOfDocumentId").OnDelete(DeleteBehavior.Restrict);
            });

        modelBuilder.Entity("Domain.MaterialUnitConversions.MaterialUnitConversion", b =>
            {
                b.HasOne("Domain.Materials.Material", null).WithMany().HasForeignKey("MaterialId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Domain.UnitsOfMeasure.UnitOfMeasure", null).WithMany().HasForeignKey("FromUnitId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Domain.UnitsOfMeasure.UnitOfMeasure", null).WithMany().HasForeignKey("ToBaseUnitId").OnDelete(DeleteBehavior.Restrict);
            });
#pragma warning restore 612, 618
    }
}
