\set ON_ERROR_STOP on
BEGIN TRANSACTION READ ONLY;
SET LOCAL statement_timeout = '10000ms';
SET LOCAL lock_timeout = '2000ms';
\pset tuples_only on
\pset format unaligned
\pset fieldsep '|'
SELECT 'database|PASS|1|read-only transaction established';
SELECT 'active_marker_not_dotted' || '|' || CASE WHEN count(*) = 1 AND max(active_vocabulary) = 'dotted-v1' THEN 'PASS' ELSE 'BLOCK' END || '|' || count(*) || '|exactly one active dotted-v1 marker' FROM public.authorization_policy_versions WHERE is_active;
SELECT 'legacy_permission_rows' || '|' || CASE WHEN count(*) = 0 THEN 'PASS' ELSE 'WARN' END || '|' || count(*) || '|legacy catalog rows are migration-managed; mapping and parity checks decide whether cutover is safe' FROM public.permissions WHERE code LIKE '%:%';
SELECT 'unknown_permission_rows' || '|' || CASE WHEN count(*) = 0 THEN 'PASS' ELSE 'BLOCK' END || '|' || count(*) || '|permission rows outside the approved dotted or known legacy catalogs' FROM public.permissions WHERE code <> ALL (ARRAY['asset.view','audit.view','custody.assign','organization.view','organization.manage','admin.role.view','admin.role.manage','catalog.manage','catalog.view','warehouse.manage','warehouse.view','inventory.view','document.view','document.create','document.update','document.submit','document.post','document.reject','document.cancel','document.reverse','count.view','count.plan','count.enter','count.complete','count.close','admin.user.view','admin.user.manage','document.revise','report.view','users:access','organizations:view','organizations:manage','sites:view','sites:manage','org-units:view','org-units:manage','employees:view','employees:manage','roles:view','roles:manage','units-of-measure:view','units-of-measure:manage','material-domains:manage','material-categories:manage','material-families:manage','materials:view','materials:manage','warehouses:view','warehouses:manage','inventory:view','assets:view','custody:view','custody:manage','warehouse-capabilities:manage','warehouse-material-settings:manage','warehouse-documents:view','warehouse-documents:create','warehouse-documents:edit','warehouse-documents:submit','warehouse-documents:cancel','warehouse-documents:review','warehouse-documents:reverse','inventory-counts:view','inventory-counts:plan','inventory-counts:enter-actual','inventory-counts:review','audit-logs:view']);
SELECT 'missing_legacy_mappings' || '|' || CASE WHEN count(*) = 0 THEN 'PASS' ELSE 'BLOCK' END || '|' || count(*) || '|legacy rows without approved dotted mapping history' FROM public.permissions p WHERE p.code LIKE '%:%' AND NOT EXISTS (SELECT 1 FROM public.permission_code_mappings m WHERE m.mapping_version = 1 AND m.old_code = p.code AND m.new_code LIKE '%.%');
SELECT 'legacy_role_grants' || '|' || CASE WHEN count(*) = 0 THEN 'PASS' ELSE 'WARN' END || '|' || count(*) || '|legacy grants are migration-managed; legacy_role_grant_parity must be PASS before cutover' FROM public.role_permissions rp JOIN public.permissions p ON p.id = rp.permission_id WHERE p.code LIKE '%:%';
SELECT 'legacy_allowed_scope_rows' || '|' || CASE WHEN count(*) = 0 THEN 'PASS' ELSE 'WARN' END || '|' || count(*) || '|legacy scopes are migration-managed; legacy_scope_parity must be PASS before cutover' FROM public.permission_allowed_scope_types pas JOIN public.permissions p ON p.id = pas.permission_id WHERE p.code LIKE '%:%';
SELECT 'legacy_role_grant_parity' || '|' || CASE WHEN count(*) = 0 THEN 'PASS' ELSE 'BLOCK' END || '|' || count(*) || '|legacy role grants without every mapped dotted grant (approved WH_MGR count-entry divergence excluded)' FROM public.role_permissions rp JOIN public.permissions p ON p.id = rp.permission_id WHERE p.code LIKE '%:%' AND NOT (rp.role_id = '00000000-0000-0000-0000-000000000003' AND p.code = 'inventory-counts:enter-actual') AND EXISTS (SELECT 1 FROM public.permission_code_mappings m WHERE m.mapping_version = 1 AND m.old_code = p.code AND NOT EXISTS (SELECT 1 FROM public.role_permissions mapped_rp JOIN public.permissions mapped_p ON mapped_p.id = mapped_rp.permission_id WHERE mapped_rp.role_id = rp.role_id AND mapped_p.code = m.new_code));
SELECT 'legacy_scope_parity' || '|' || CASE WHEN count(*) = 0 THEN 'PASS' ELSE 'BLOCK' END || '|' || count(*) || '|legacy allowed scopes without every mapped dotted scope' FROM public.permission_allowed_scope_types pas JOIN public.permissions p ON p.id = pas.permission_id WHERE p.code LIKE '%:%' AND EXISTS (SELECT 1 FROM public.permission_code_mappings m WHERE m.mapping_version = 1 AND m.old_code = p.code AND NOT EXISTS (SELECT 1 FROM public.permissions mapped_p JOIN public.permission_allowed_scope_types mapped_pas ON mapped_pas.permission_id = mapped_p.id WHERE mapped_p.code = m.new_code AND mapped_pas.scope_type = pas.scope_type));
SELECT 'dotted_grants_without_scope' || '|' || CASE WHEN count(*) = 0 THEN 'PASS' ELSE 'BLOCK' END || '|' || count(*) || '|dotted role grants with no intersection between role and permission allowed scopes' FROM public.role_permissions rp JOIN public.permissions p ON p.id = rp.permission_id WHERE p.code LIKE '%.%' AND NOT EXISTS (SELECT 1 FROM public.permission_allowed_scope_types pas WHERE pas.permission_id = rp.permission_id AND pas.scope_type IN (SELECT ras.scope_type FROM public.role_allowed_scope_types ras WHERE ras.role_id = rp.role_id));
SELECT 'seeded_role_grant_drift' || '|' || CASE WHEN count(*) = 0 THEN 'PASS' ELSE 'BLOCK' END || '|' || count(*) || '|seeded dotted role grant set differs from the approved policy' FROM (WITH expected(role_id, codes) AS (VALUES ('00000000-0000-0000-0000-000000000001'::uuid, ARRAY['catalog.view','catalog.manage','organization.view','organization.manage','warehouse.view','warehouse.manage','admin.user.view','admin.user.manage','admin.role.view','admin.role.manage']), ('00000000-0000-0000-0000-000000000002'::uuid, ARRAY['catalog.view','organization.view','warehouse.view','inventory.view','document.view','document.create','document.update','document.submit','document.revise','document.cancel','count.view','count.enter','asset.view','custody.assign','report.view']), ('00000000-0000-0000-0000-000000000003'::uuid, ARRAY['catalog.view','organization.view','warehouse.view','inventory.view','document.view','count.view','asset.view','report.view','document.create','document.update','document.post','document.reject','document.cancel','document.reverse','count.plan','count.complete','count.close']), ('00000000-0000-0000-0000-000000000004'::uuid, ARRAY['catalog.view','organization.view','warehouse.view','inventory.view','document.view','count.view','asset.view','audit.view','report.view'])), expected_pairs AS (SELECT role_id, code FROM expected CROSS JOIN LATERAL unnest(codes) AS code), actual_pairs AS (SELECT rp.role_id, p.code FROM public.role_permissions rp JOIN public.permissions p ON p.id = rp.permission_id WHERE p.code LIKE '%.%' AND rp.role_id IN (SELECT role_id FROM expected)), drift AS ((SELECT role_id, code FROM expected_pairs EXCEPT SELECT role_id, code FROM actual_pairs) UNION (SELECT role_id, code FROM actual_pairs EXCEPT SELECT role_id, code FROM expected_pairs)) SELECT role_id, code FROM drift) drift;
SELECT 'seeded_scope_drift' || '|' || CASE WHEN count(*) = 0 THEN 'PASS' ELSE 'BLOCK' END || '|' || count(*) || '|seeded role scope set differs from the approved policy' FROM (WITH expected(role_id, scope_types) AS (VALUES ('00000000-0000-0000-0000-000000000001'::uuid, ARRAY['Enterprise']), ('00000000-0000-0000-0000-000000000002'::uuid, ARRAY['Warehouse']), ('00000000-0000-0000-0000-000000000003'::uuid, ARRAY['Enterprise','Site','Warehouse']), ('00000000-0000-0000-0000-000000000004'::uuid, ARRAY['Enterprise','Site','Warehouse'])), expected_pairs AS (SELECT role_id, scope_type FROM expected CROSS JOIN LATERAL unnest(scope_types) AS scope_type), actual_pairs AS (SELECT role_id, scope_type::text FROM public.role_allowed_scope_types WHERE role_id IN (SELECT role_id FROM expected)), drift AS ((SELECT role_id, scope_type FROM expected_pairs EXCEPT SELECT role_id, scope_type FROM actual_pairs) UNION (SELECT role_id, scope_type FROM actual_pairs EXCEPT SELECT role_id, scope_type FROM expected_pairs)) SELECT role_id, scope_type FROM drift) drift;
SELECT 'unknown_mapping_targets' || '|' || CASE WHEN count(*) = 0 THEN 'PASS' ELSE 'BLOCK' END || '|' || count(*) || '|mapping targets outside approved dotted catalog' FROM public.permission_code_mappings m WHERE m.mapping_version = 1 AND m.new_code <> ALL (ARRAY['asset.view','audit.view','custody.assign','organization.view','organization.manage','admin.role.view','admin.role.manage','catalog.manage','catalog.view','warehouse.manage','warehouse.view','inventory.view','document.view','document.create','document.update','document.submit','document.post','document.reject','document.cancel','document.reverse','count.view','count.plan','count.enter','count.complete','count.close','admin.user.view','admin.user.manage','document.revise','report.view']);
SELECT 'wildcard_permission_rows' || '|' || CASE WHEN count(*) = 0 THEN 'PASS' ELSE 'BLOCK' END || '|' || count(*) || '|wildcard or generic permission codes' FROM public.permissions WHERE code LIKE '%*%' OR code LIKE 'any:%';
COMMIT;
