using SharedKernel;

namespace Application.Abstractions.Storage;

/// <summary>
/// Stores attachment file content outside the source tree, addressed only by an opaque
/// <see cref="StoredFile.StorageKey"/> generated by the implementation - never the client's
/// filename (M3-PLAN.md §1.4). The SHA-256 checksum is computed server-side while writing, so the
/// hash always matches the bytes actually persisted.
/// </summary>
public interface IFileStorage
{
    Task<Result<StoredFile>> SaveAsync(Stream content, CancellationToken cancellationToken);

    Task<Result<Stream>> OpenAsync(string storageKey, CancellationToken cancellationToken);

    Task<Result> DeleteAsync(string storageKey, CancellationToken cancellationToken);
}

/// <summary>The result of a successful <see cref="IFileStorage.SaveAsync"/> call.</summary>
public sealed record StoredFile(string StorageKey, long FileSize, string Checksum);
